spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/*.xml
redis:
  user:
    expire: 7200

LoginUser:
  user:
    password: 6
    phone: 11



# 或者在 jvm 参数上加 -Dspring.profiles.active=prod