spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/*.xml
redis:
  user:
    expire: 7200

loginUser:
  user:
    password:
      length:
        min: 6
        max: 12
    phone:
      length: 11



# 或者在 jvm 参数上加 -Dspring.profiles.active=prod